import Head from 'next/head';
import React from 'react';

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>this is header</header>
      <main>{children}</main>
      <footer>this is footer</footer>
    </div>
  );
};

export default Layout;
